name: V-Shop CI Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Download JUnit Console
      run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar -O junit.jar
        
    - name: Compile and Run Tests
      run: |
        javac -cp junit.jar src/*.java
        java -jar junit.jar -cp src --scan-class-path
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=toriiend_vshop-voucher
          -Dsonar.organization=toriiend
          -Dsonar.sources=src
          -Dsonar.java.binaries=.

          
  non-functional-testing:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Tích hợp Performance Test (Poka-Yoke cho tốc độ)
      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: tests/performance-test.js

  acceptance-and-chaos:
    needs: non-functional-testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Tích hợp Chaos Engineering (Jidoka cho tính bền bỉ)
      - name: Chaos Scenario - Voucher Service Outage
        run: |
          chmod +x scripts/chaos-scenario.sh
          ./scripts/chaos-scenario.sh      
